name: GitHub Actions Demo

on:
  issue_comment:
    types: [created]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Comment
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
